allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
ext {
    android = [
            compileSdkVersion              : 33, // Update as needed
            buildToolsVersion              : "33.0.2", // Update as needed
            minSdkVersion                  : 21, // Minimum supported Android version
            targetSdkVersion               : 33, // Target Android version
            selfChassisLibraryVersionCode  : 1, // Version code for the library
            selfChassisLibraryersionName   : "1.0", // Version name for the library
    ]

    dependencies = [
        okhttp     : "com.squareup.okhttp3:okhttp:4.12.0", // Latest stable version as of October 2023
        gson       : "com.google.code.gson:gson:2.10.1",   // Latest stable version as of October 2023
        eventbus   : "org.greenrobot:eventbus:3.3.1"       // Latest stable version as of October 2023
    ]
}
